# Generated by Django 3.2.7 on 2022-05-02 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_relationship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
